print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/10740244/Desktop/2670/StarCatcherProtoype0.3/Assets/Materials/Land1.ma"`)
{		
	file -o "/Users/10740244/Desktop/2670/StarCatcherProtoype0.3/Assets/Materials/Land1.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/10740244/Desktop/2670/StarCatcherProtoype0.3/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/10740244/Desktop/2670/StarCatcherProtoype0.3/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/10740244/Desktop/2670/StarCatcherProtoype0.3/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
